/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScoreEntry = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });

export const idlService = IDL.Service({
  'addScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'createRoom' : IDL.Func([], [IDL.Text], []),
  'getInput' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getRoomInfo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Opt(
          IDL.Record({ 'guestJoined' : IDL.Bool, 'hostJoined' : IDL.Bool })
        ),
      ],
      ['query'],
    ),
  'getState' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
  'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
  'joinRoom' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'sendInput' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'sendState' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScoreEntry = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });
  
  return IDL.Service({
    'addScore' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'createRoom' : IDL.Func([], [IDL.Text], []),
    'getInput' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getRoomInfo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Opt(
            IDL.Record({ 'guestJoined' : IDL.Bool, 'hostJoined' : IDL.Bool })
          ),
        ],
        ['query'],
      ),
    'getState' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], []),
    'getTopScores' : IDL.Func([], [IDL.Vec(ScoreEntry)], ['query']),
    'joinRoom' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'sendInput' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'sendState' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };